package com.asset.manage.dao;

import com.asset.manage.model.MyFile;
import com.asset.manage.model.MyFileExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MyFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated
     */
    int countByExample(MyFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated
     */
    int deleteByExample(MyFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated
     */
    int insert(MyFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated
     */
    int insertSelective(MyFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated
     */
    List<MyFile> selectByExample(MyFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated
     */
    MyFile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MyFile record, @Param("example") MyFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MyFile record, @Param("example") MyFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MyFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MyFile record);
}