package com.asset.manage.model;

import java.util.Date;

public class Asset {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.descreption
     *
     * @mbggenerated
     */
    private String descreption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.image_id
     *
     * @mbggenerated
     */
    private String imageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.join_time
     *
     * @mbggenerated
     */
    private Date joinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.join_id
     *
     * @mbggenerated
     */
    private String joinId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.join_name
     *
     * @mbggenerated
     */
    private String joinName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.dept_id
     *
     * @mbggenerated
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.sum_num
     *
     * @mbggenerated
     */
    private Integer sumNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.borrow_num
     *
     * @mbggenerated
     */
    private Integer borrowNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.dept_name
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.type_id
     *
     * @mbggenerated
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.type_name
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.id
     *
     * @return the value of asset.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.id
     *
     * @param id the value for asset.id
     *
     * @mbggenerated
     */
    public Asset setId(String id) {
        this.id = id == null ? null : id.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.name
     *
     * @return the value of asset.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.name
     *
     * @param name the value for asset.name
     *
     * @mbggenerated
     */
    public Asset setName(String name) {
        this.name = name == null ? null : name.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.descreption
     *
     * @return the value of asset.descreption
     *
     * @mbggenerated
     */
    public String getDescreption() {
        return descreption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.descreption
     *
     * @param descreption the value for asset.descreption
     *
     * @mbggenerated
     */
    public Asset setDescreption(String descreption) {
        this.descreption = descreption == null ? null : descreption.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.image_id
     *
     * @return the value of asset.image_id
     *
     * @mbggenerated
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.image_id
     *
     * @param imageId the value for asset.image_id
     *
     * @mbggenerated
     */
    public Asset setImageId(String imageId) {
        this.imageId = imageId == null ? null : imageId.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.remark
     *
     * @return the value of asset.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.remark
     *
     * @param remark the value for asset.remark
     *
     * @mbggenerated
     */
    public Asset setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.join_time
     *
     * @return the value of asset.join_time
     *
     * @mbggenerated
     */
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.join_time
     *
     * @param joinTime the value for asset.join_time
     *
     * @mbggenerated
     */
    public Asset setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.join_id
     *
     * @return the value of asset.join_id
     *
     * @mbggenerated
     */
    public String getJoinId() {
        return joinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.join_id
     *
     * @param joinId the value for asset.join_id
     *
     * @mbggenerated
     */
    public Asset setJoinId(String joinId) {
        this.joinId = joinId == null ? null : joinId.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.join_name
     *
     * @return the value of asset.join_name
     *
     * @mbggenerated
     */
    public String getJoinName() {
        return joinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.join_name
     *
     * @param joinName the value for asset.join_name
     *
     * @mbggenerated
     */
    public Asset setJoinName(String joinName) {
        this.joinName = joinName == null ? null : joinName.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.dept_id
     *
     * @return the value of asset.dept_id
     *
     * @mbggenerated
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.dept_id
     *
     * @param deptId the value for asset.dept_id
     *
     * @mbggenerated
     */
    public Asset setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.sum_num
     *
     * @return the value of asset.sum_num
     *
     * @mbggenerated
     */
    public Integer getSumNum() {
        return sumNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.sum_num
     *
     * @param sumNum the value for asset.sum_num
     *
     * @mbggenerated
     */
    public Asset setSumNum(Integer sumNum) {
        this.sumNum = sumNum;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.borrow_num
     *
     * @return the value of asset.borrow_num
     *
     * @mbggenerated
     */
    public Integer getBorrowNum() {
        return borrowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.borrow_num
     *
     * @param borrowNum the value for asset.borrow_num
     *
     * @mbggenerated
     */
    public Asset setBorrowNum(Integer borrowNum) {
        this.borrowNum = borrowNum;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.dept_name
     *
     * @return the value of asset.dept_name
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.dept_name
     *
     * @param deptName the value for asset.dept_name
     *
     * @mbggenerated
     */
    public Asset setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.type_id
     *
     * @return the value of asset.type_id
     *
     * @mbggenerated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.type_id
     *
     * @param typeId the value for asset.type_id
     *
     * @mbggenerated
     */
    public Asset setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.type_name
     *
     * @return the value of asset.type_name
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.type_name
     *
     * @param typeName the value for asset.type_name
     *
     * @mbggenerated
     */
    public Asset setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.state
     *
     * @return the value of asset.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.state
     *
     * @param state the value for asset.state
     *
     * @mbggenerated
     */
    public Asset setState(String state) {
        this.state = state == null ? null : state.trim();
        return this;
    }
}