package com.asset.manage.model;

import java.util.Date;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mydept.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mydept.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mydept.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mydept.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mydept.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mydept.id
     *
     * @return the value of mydept.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mydept.id
     *
     * @param id the value for mydept.id
     *
     * @mbggenerated
     */
    public Dept setId(String id) {
        this.id = id == null ? null : id.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mydept.name
     *
     * @return the value of mydept.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mydept.name
     *
     * @param name the value for mydept.name
     *
     * @mbggenerated
     */
    public Dept setName(String name) {
        this.name = name == null ? null : name.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mydept.create_time
     *
     * @return the value of mydept.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mydept.create_time
     *
     * @param createTime the value for mydept.create_time
     *
     * @mbggenerated
     */
    public Dept setCreateTime(Date createTime) {
        this.createTime = createTime;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mydept.remark
     *
     * @return the value of mydept.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mydept.remark
     *
     * @param remark the value for mydept.remark
     *
     * @mbggenerated
     */
    public Dept setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mydept.state
     *
     * @return the value of mydept.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mydept.state
     *
     * @param state the value for mydept.state
     *
     * @mbggenerated
     */
    public Dept setState(Integer state) {
        this.state = state;
        return this;
    }
}