package com.asset.manage.model;

import java.util.Date;

public class Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.type_id
     *
     * @mbggenerated
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.id
     *
     * @return the value of record.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.id
     *
     * @param id the value for record.id
     *
     * @mbggenerated
     */
    public Record setId(String id) {
        this.id = id == null ? null : id.trim();
		return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.user_id
     *
     * @return the value of record.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.user_id
     *
     * @param userId the value for record.user_id
     *
     * @mbggenerated
     */
    public Record setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
		return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.user_name
     *
     * @return the value of record.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.user_name
     *
     * @param userName the value for record.user_name
     *
     * @mbggenerated
     */
    public Record setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
		return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.create_time
     *
     * @return the value of record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.create_time
     *
     * @param createTime the value for record.create_time
     *
     * @mbggenerated
     */
    public Record setCreateTime(Date createTime) {
        this.createTime = createTime;
		return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.remark
     *
     * @return the value of record.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.remark
     *
     * @param remark the value for record.remark
     *
     * @mbggenerated
     */
    public Record setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
		return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.type_id
     *
     * @return the value of record.type_id
     *
     * @mbggenerated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.type_id
     *
     * @param typeId the value for record.type_id
     *
     * @mbggenerated
     */
    public Record setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
		return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.state
     *
     * @return the value of record.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.state
     *
     * @param state the value for record.state
     *
     * @mbggenerated
     */
    public Record setState(Integer state) {
        this.state = state;
		return this;
    }
}