package com.asset.manage.model;

/**
 * 角色类相关
 * 
 * @author Administrator
 *
 */
public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated
     */
    public Role setId(String id) {
        this.id = id == null ? null : id.trim();
		return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbggenerated
     */
    public Role setName(String name) {
        this.name = name == null ? null : name.trim();
		return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.remark
     *
     * @return the value of role.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.remark
     *
     * @param remark the value for role.remark
     *
     * @mbggenerated
     */
    public Role setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
		return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.state
     *
     * @return the value of role.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.state
     *
     * @param state the value for role.state
     *
     * @mbggenerated
     */
    public Role setState(Integer state) {
        this.state = state;
		return this;
    }
}