package com.asset.manage.model;

import java.util.Date;

public class Type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mytype.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mytype.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mytype.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mytype.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mytype.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mytype.pid
     *
     * @mbggenerated
     */
    private String pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mytype.id
     *
     * @return the value of mytype.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mytype.id
     *
     * @param id the value for mytype.id
     *
     * @mbggenerated
     */
    public Type setId(String id) {
        this.id = id == null ? null : id.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mytype.name
     *
     * @return the value of mytype.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mytype.name
     *
     * @param name the value for mytype.name
     *
     * @mbggenerated
     */
    public Type setName(String name) {
        this.name = name == null ? null : name.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mytype.create_time
     *
     * @return the value of mytype.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mytype.create_time
     *
     * @param createTime the value for mytype.create_time
     *
     * @mbggenerated
     */
    public Type setCreateTime(Date createTime) {
        this.createTime = createTime;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mytype.state
     *
     * @return the value of mytype.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mytype.state
     *
     * @param state the value for mytype.state
     *
     * @mbggenerated
     */
    public Type setState(String state) {
        this.state = state == null ? null : state.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mytype.remark
     *
     * @return the value of mytype.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mytype.remark
     *
     * @param remark the value for mytype.remark
     *
     * @mbggenerated
     */
    public Type setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mytype.pid
     *
     * @return the value of mytype.pid
     *
     * @mbggenerated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mytype.pid
     *
     * @param pid the value for mytype.pid
     *
     * @mbggenerated
     */
    public Type setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
        return this;
    }
}